[package]
org = "anjana"
name = "azf_demo"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax" 
name = "azure_functions"
version = "3.0.0-alpha.2"
repository="local"
